name : Orion-K 
run-name: ${{github.actor}}'s workflows
on : 
  push :
    tag :
      - "v*"
jobs:
  build-image:
    runs-on : ubuntu-latest
    steps :
      - name : Checkout Source Code
        uses: actions/checkout@v6

      - name: Login GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build docker image to push 
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          run: docker build . -t ghcr.io/${{github.actor}}/orion-k:latest

      - name: Push docker image to container registry
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          run: docker push ghcr.io/${{github.actor}}/orion-k:latest 
      
  uploads-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: actions/checkout@v4

      - name: Install all Deps
        run : go mod tidy

      - name: Build App
        run : go build -o orion_k main.go

      - name: Uploads Artifact
        uses: actions/upload-artifact@v7
        with:
          name: orion-k
          id: orion-k-id
          path: orion_k

  release-app:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: action/download-artifact@v8
        with:
          name: orion-K
          path: orion_k

      - name: Compress Artifact
        run: zip -r orion-k.zip ./*

      - name: Release Final App
        uses: softprops/action-gh-release@v3
        with:
          files: |
            orion-k.zip

